name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Client clean build
      run: ./wordpress-client/gradlew clean build
    - name: Demo clean build
      run: ./demo/gradlew clean build
